package frc.trigon.robot.constants;

import edu.wpi.first.wpilibj.RobotController;
import edu.wpi.first.wpilibj2.command.button.Trigger;
import frc.trigon.lib.hardware.misc.KeyboardController;
import frc.trigon.lib.hardware.misc.XboxController;
import frc.trigon.robot.RobotContainer;
import frc.trigon.robot.misc.matchTracker.MatchTracker;

public class OperatorConstants {
    public static final double DRIVER_CONTROLLER_DEADBAND = 0.07;
    private static final int DRIVER_CONTROLLER_PORT = 0;
    private static final int
            DRIVER_CONTROLLER_RIGHT_STICK_EXPONENT = 1,
            DRIVER_CONTROLLER_LEFT_STICK_EXPONENT = 1;
    public static final XboxController DRIVER_CONTROLLER = new XboxController(
            DRIVER_CONTROLLER_PORT, DRIVER_CONTROLLER_RIGHT_STICK_EXPONENT, DRIVER_CONTROLLER_LEFT_STICK_EXPONENT, DRIVER_CONTROLLER_DEADBAND
    );
    public static final KeyboardController OPERATOR_CONTROLLER = new KeyboardController();
    private static final double ARE_CAMERAS_DISCONNECTED_CHECK_DEBOUNCE_SECONDS = 3;

    public static final double
            POV_DIVIDER = 2,
            TRANSLATION_STICK_SPEED_DIVIDER = 1,
            ROTATION_STICK_SPEED_DIVIDER = 1;

    public static final Trigger
            RESET_HEADING_TRIGGER = DRIVER_CONTROLLER.y(),
            RESET_HOOD_TRIGGER = OPERATOR_CONTROLLER.a().or(DRIVER_CONTROLLER.b()),
            TOGGLE_BRAKE_TRIGGER = OPERATOR_CONTROLLER.g().or(RobotController::getUserButton),
            DEBUGGING_TRIGGER = OPERATOR_CONTROLLER.f2(),
            SHOOTING_MAP_CALIBRATION_TRIGGER = OPERATOR_CONTROLLER.f3(),
            TELEPORTATION_FOR_SIMULATION_SHOOTING_MAP_CALIBRATION_TRIGGER = OPERATOR_CONTROLLER.f4(),
            RESET_POSE_TO_FIXED_SHOOTING_LOCATION_TRIGGER = OPERATOR_CONTROLLER.f5(),
            FORWARD_QUASISTATIC_CHARACTERIZATION_TRIGGER = OPERATOR_CONTROLLER.right(),
            BACKWARD_QUASISTATIC_CHARACTERIZATION_TRIGGER = OPERATOR_CONTROLLER.left(),
            FORWARD_DYNAMIC_CHARACTERIZATION_TRIGGER = OPERATOR_CONTROLLER.up(),
            BACKWARD_DYNAMIC_CHARACTERIZATION_TRIGGER = OPERATOR_CONTROLLER.down(),
            CAMERAS_DISCONNECTED_TRIGGER = new Trigger(() -> !RobotContainer.ROBOT_POSE_ESTIMATOR.hasUpdateFromCameras()).debounce(ARE_CAMERAS_DISCONNECTED_CHECK_DEBOUNCE_SECONDS);
    public static final Trigger
            SHOOTING_TRIGGER = DRIVER_CONTROLLER.rightStick().or(OPERATOR_CONTROLLER.d()),
            SET_TARGET_FIXED_SCORING_BETWEEN_TOWER_AND_HUB_TRIGGER = DRIVER_CONTROLLER.povUp().or(OPERATOR_CONTROLLER.i()),
            SET_TARGET_FIXED_SCORING_IN_FRONT_OF_TOWER_TRIGGER = DRIVER_CONTROLLER.povDown().or(OPERATOR_CONTROLLER.k()),
            SET_TARGET_FIXED_SCORING_CLOSEST_TRENCH_TRIGGER = DRIVER_CONTROLLER.povLeft(),
            SET_TARGET_FIXED_SCORING_CLOSEST_SIDE_OF_TOWER_TRIGGER = DRIVER_CONTROLLER.povRight(),
            SET_TARGET_FIXED_SCORING_RIGHT_TRENCH_TRIGGER = OPERATOR_CONTROLLER.o(),
            SET_TARGET_FIXED_SCORING_LEFT_TRENCH_TRIGGER = OPERATOR_CONTROLLER.u(),
            SET_TARGET_FIXED_SCORING_RIGHT_OF_TOWER_TRIGGER = OPERATOR_CONTROLLER.l(),
            SET_TARGET_FIXED_SCORING_LEFT_OF_TOWER_TRIGGER = OPERATOR_CONTROLLER.j(),
            SET_TARGET_FIXED_SCORING_BACK_RIGHT_TRIGGER = OPERATOR_CONTROLLER.equals(),
            SET_TARGET_FIXED_SCORING_BACK_LEFT_TRIGGER = OPERATOR_CONTROLLER.minus(),
            FIXED_SHOOTING_AT_HUB_TRIGGER = DRIVER_CONTROLLER.back().or(OPERATOR_CONTROLLER.s()),
            FIXED_DELIVERY_TRIGGER = DRIVER_CONTROLLER.leftBumper().or(OPERATOR_CONTROLLER.f()),
            EJECT_FROM_INTAKE_TRIGGER = DRIVER_CONTROLLER.a().or(OPERATOR_CONTROLLER.e()),
            EJECT_FROM_SHOOTER_TRIGGER = DRIVER_CONTROLLER.x().or(OPERATOR_CONTROLLER.r()),
            ENABLE_OVERRIDE_FIXED_SWERVE_AIM_TRIGGER = OPERATOR_CONTROLLER.m(),
            DISABLE_OVERRIDE_FIXED_SWERVE_AIM_TRIGGER = OPERATOR_CONTROLLER.n(),
            LOWER_HOOD_TRIGGER = OPERATOR_CONTROLLER.q(),
            IS_ANY_SHOOTING_TRIGGER_ACTIVE = SHOOTING_TRIGGER.or(FIXED_SHOOTING_AT_HUB_TRIGGER).or(FIXED_DELIVERY_TRIGGER).or(EJECT_FROM_SHOOTER_TRIGGER),
            PREPARE_FOR_FIXED_SHOOTING_TRIGGER = OPERATOR_CONTROLLER.semicolon().and(IS_ANY_SHOOTING_TRIGGER_ACTIVE.negate()),
            PREPARE_FOR_SHOOTING_TRIGGER = OPERATOR_CONTROLLER.v().and(IS_ANY_SHOOTING_TRIGGER_ACTIVE.negate());
    public final static Trigger
            PRELOAD_TRIGGER = (OPERATOR_CONTROLLER.x().or(DRIVER_CONTROLLER.start())).and(IS_ANY_SHOOTING_TRIGGER_ACTIVE.negate()),
            CLOSE_INTAKE_WITHOUT_SHOOTING_TRIGGER = DRIVER_CONTROLLER.leftStick().and(IS_ANY_SHOOTING_TRIGGER_ACTIVE.negate()),
            INTAKE_TRIGGER = (DRIVER_CONTROLLER.leftTrigger().or(OPERATOR_CONTROLLER.b())).and(IS_ANY_SHOOTING_TRIGGER_ACTIVE.negate()),
            TRENCH_ASSIST_TRIGGER = DRIVER_CONTROLLER.rightBumper(),
            HUB_ACTIVE_STATE_CHANGED_TRIGGER = new Trigger(MatchTracker::hasHubActiveStateChanged),
            OPEN_INTAKE_DEFAULT_COMMAND = OPERATOR_CONTROLLER.t(),
            CLOSE_INTAKE_DEFAULT_COMMAND = OPERATOR_CONTROLLER.y(),
            LOAD_NOW_TRIGGER = OPERATOR_CONTROLLER.w().or(DRIVER_CONTROLLER.leftStick());
}